apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: webgame-cluster
  region: us-east-1
  version: "1.30"

# Activate OIDC
iam:
  withOIDC: true

# use existing VPC / Subnet
vpc:
  id: ${VPC_ID}
  subnets:
    public:
      us-east-1b:
        id: ${PUBLIC_SUBNET_1b}
      us-east-1a:
        id: ${PUBLIC_SUBNET_1a}

# EKS node（Spot Instance）
managedNodeGroups:
  - name: public-spot-ng
    instanceTypes:
      - t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2

    # Not to create the EKS nodes in the private subnet
    privateNetworking: false
    # Spot Instance
    # spot: true

    iam:
      instanceRoleARN: ${INSTANCE_ROLE_ARN}

    labels:
      role: worker
      lifecycle: spot
